#ifndef VL53L0X_REGISTERS_H
#define VL53L0X_REGISTERS_H

#include <stdint.h>

// VL53L0X register addresses
#define VL53L0X_REG_SYSRANGE_START              0x00
#define VL53L0X_REG_SYSTEM_INTERRUPT_CLEAR      0x0B
#define VL53L0X_REG_RESULT_INTERRUPT_STATUS     0x13
#define VL53L0X_REG_RESULT_RANGE_STATUS         0x14
#define VL53L0X_REG_RESULT_CORE_AMBIENT_WINDOW_EVENTS_HI 0xBC
#define VL53L0X_REG_RESULT_CORE_RANGING_TOTAL_EVENTS_HI   0xC0

#define VL53L0X_REG_IDENTIFICATION_MODEL_ID       0xC0
#define VL53L0X_REG_RESULT_RANGE_VALUE_HI         0x1E
#define VL53L0X_REG_RESULT_RANGE_VALUE_LO         0x1F

#define VL53L0X_MODEL_ID 0xEE

#endif // VL53L0X_REGISTERS_H
